#PBS -l walltime=96:0:00
#PBS -l nodes=8:ppn=28
#PBS -N rawtest00
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=rawtest00
#source $HOME/.bashrc


cd "$PBS_O_WORKDIR"
#zipper
./loopscript zipper &> $PBS_O_WORKDIR/zipper.log&
zipper_PID=$!


mpiexec -n 224 ./lsp-10-3d -r $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.$(date +%y%m%d%H%M).o.txt

kill $zipper_PID
./zipper -a >$PBS_O_WORKDIR
