#!/usr/bin/env bash
cp ../start ../terminate ../chmem  ./

PBSBASE=hotwater2d_w_baseline
mkdir -p $PBSBASE
./genlsp.py --lim="(-40,10,-20,20)" \
            --res="(2000,1600)" \
            --description="two colors with hotwater2d, baseline" \
            --domains=48 \
            --time=300e-15>$PBSBASE/$PBSBASE.lsp
./genpbs.py --domains=48 --pbsbase=$PBSBASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$PBSBASE/$PBSBASE.pbs
cp *.dat $PBSBASE/

PBSBASE=hotwater2d_2w
mkdir -p $PBSBASE

#hack, but it works
TWOOMEGA="\
coefficients \
1.00 7.8e-5 2.17e-4 \
0.36 3.9e-5 2.17e-4 end"
./genlsp.py --lim="(-40,10,-20,20)" \
            --res="(2000,1600)" \
            --domains=48 \
            --description="two colors with hotwater2d, 2w" \
            --time=300e-15 |\
    sed 's/type *19.*$/type 85/' |\
    sed 's/^.*\\lambda.*$//' |\
    sed 's/^.*coefficients 7.80*e-0*5.*$/'"${TWOOMEGA}"/ \
        >$PBSBASE/$PBSBASE.lsp
./genpbs.py --domains=48 --pbsbase=$PBSBASE |\
    sed 's/lsp-10-xy/lsp-10-xy-multilaser/' |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$PBSBASE/$PBSBASE.pbs

cp *.dat $PBSBASE/


PBSBASE=hotwater2d_2w_wider
mkdir -p $PBSBASE

#hack, but it works
TWOOMEGA="\
coefficients \
1.00 7.8e-5 2.17e-4 \
0.36 3.9e-5 2.17e-4 end"
./genlsp.py --lim="(-40,10,-25,25)" \
            --res="(2000,2000)" \
            --domains=48 \
            --description="wider two colors with hotwater2d, 2w" \
            --time=300e-15 |\
    sed 's/type *19.*$/type 85/' |\
    sed 's/^.*\\lambda.*$//' |\
    sed 's/^.*coefficients 7.80*e-0*5.*$/'"${TWOOMEGA}"/ \
        >$PBSBASE/$PBSBASE.lsp
./genpbs.py --domains=48 --pbsbase=$PBSBASE |\
    sed 's/lsp-10-xy/lsp-10-xy-multilaser/' |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$PBSBASE/$PBSBASE.pbs

cp *.dat $PBSBASE/

#super long
PBSBASE=hotwater2d_2w_superlong
mkdir -p $PBSBASE

#hack, but it works
TWOOMEGA="\
coefficients \
1.00 7.8e-5 2.17e-4 \
0.36 3.9e-5 2.17e-4 end"
./genlsp.py --lim="(-85,10,-20,20)" \
            --tlim="(-75, 0, -9,9)" \
            --res="(3800,1600)" \
            --domains=96 \
            --description="huuuger two colors with hotwater2d, 2w" \
            --fp="(-50,0,0)" \
            --time=350e-15 |\
    sed 's/type *19.*$/type 85/' |\
    sed 's/^.*\\lambda.*$//' |\
    sed 's/^.*coefficients 7.80*e-0*5.*$/'"${TWOOMEGA}"/ \
        >$PBSBASE/$PBSBASE.lsp
./genpbs.py --domains=96 --pbsbase=$PBSBASE |\
    sed 's/lsp-10-xy/lsp-10-xy-multilaser/' |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$PBSBASE/$PBSBASE.pbs

cp sine700points.dat superlong.dat $PBSBASE/

