#!/bin/bash

if [ $# -eq 1 ]; then 
    D=$1;
else
    D=$PWD;
fi;
NAME=`basename $D`
cd $D
MATCH="$(qstat | grep "$NAME" | head -n 1 | cut -d . -f 1)"
if [ -n "$MATCH" ]; then
    echo killing $NAME with jobid $MATCH;
    qdel "$MATCH";
else
    echo $NAME not found
fi

