#PBS -l walltime=96:0:00
#PBS -l nodes=20:ppn=12
#PBS -N glycol_tnsa
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=glycol_tnsa
#source $HOME/.bashrc

#This outputs the name of the root node
#to the directory where you submitted this PBS job
echo $HOSTNAME > $PBS_O_WORKDIR/hostname.txt   
cat $PBS_NODEFILE | uniq > $PBS_O_WORKDIR/nodesfile.txt


cd $PBS_O_WORKDIR


mpiexec -n 240 ./lsp-10-xy $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.o.txt

