#!/usr/bin/env bash

getallsorted(){
   ls | grep $1'.*.p4$' | sort -V
}

getsorted(){
    getallsorted $1 | head -n -1
}

if [ "$1" == "-a" ]; then
    export FLDS=$(getallsorted flds);
    export SCLR=$(getallsorted sclr);
    export PMOV=$(getallsorted pmovie);
else
    export FLDS=$(getsorted flds);
    export SCLR=$(getsorted sclr);
    export PMOV=$(getsorted pmovie);
fi
JOBS=${JOBS:-4}
[ -n "$FLDS" ] && parallel -j $JOBS gzip -v ::: $FLDS || echo "no new flds"
[ -n "$SCLR" ] && parallel -j $JOBS gzip -v ::: $SCLR || echo "no new sclr"
[ -n "$PMOV" ] && parallel -j $JOBS gzip -v ::: $PMOV || echo "no new pmovie"


