#PBS -l walltime=96:0:00
#PBS -l nodes=4:ppn=12
#PBS -N 0.8um-3.46e+18-shelf=1e+18
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=0.8um-3.46e+18-shelf=1e+18
#source $HOME/.bashrc

#This outputs the name of the root node
#to the directory where you submitted this PBS job
echo $HOSTNAME > $PBS_O_WORKDIR/hostname.txt   
cat $PBS_NODEFILE | uniq > $PBS_O_WORKDIR/nodesfile.txt


cd $PBS_O_WORKDIR


mpiexec -n 48 ./lsp-10-xy $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.o.txt

