#!/usr/bin/env bash

getallsorted(){
   ls | grep $1'.*.p4$' |\
         sed s/^$1'\([0-9]\+\)\.p4$/\1/' |\
         sort -n |\
         sed 's/\(^.*$\)/'$1'\1.p4/'
}

getsorted(){
    getallsorted | head -n -1
}

if [ "$1" == "-a" ]; then
    export FLDS=$(getallsorted flds);
    export SCLR=$(getallsorted sclr);
    export PMOV=$(getallsorted pmovie);
else
    export FLDS=$(getallsorted flds);
    export SCLR=$(getallsorted sclr);
    export PMOV=$(getallsorted pmovie);
fi
[ -n "$FLDS" ] && gzip -v $FLDS || echo "no new flds"
[ -n "$SCLR" ] && gzip -v $SCLR || echo "no new sclr"
[ -n "$PMOV" ] && gzip -v $PMOV || echo "no new pmovie"


