#PBS -l walltime=9999:0:00
#PBS -l nodes=8:ppn=48
#PBS -N gaussctrl00
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=gaussctrl00
#source $HOME/.bashrc

module load openmpi-1.4.3-gnu-rpm


cd "$PBS_O_WORKDIR"
#zipper
./loopscript zipper &> $PBS_O_WORKDIR/zipper.log&
zipper_PID=$!


mpirun -np 352 -hostfile $PBS_NODEFILE ./lsp-10-3d -r $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.$(date +%y%m%d%H%M).o.txt

kill $zipper_PID
./zipper -a >$PBS_O_WORKDIR
