from pys import sd,test;
import numpy as np;
implicit_species_flag = False
h2o_species_explicit = [
    ####################################
    dict(label = 'Oxygen',
         implicit_species_flag = implicit_species_flag,
         charge = 0,
         mass = 29164.4,
         atomic_number = 8,
         scattering_flag = False,),
    dict(label = 'O+',
         implicit_species_flag = implicit_species_flag,
         charge = 1,
         mass = 29163.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O++',
         implicit_species_flag = implicit_species_flag,
         charge = 2,
         mass = 29162.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O3+',
         implicit_species_flag = implicit_species_flag,
         charge = 3,
         mass = 29161.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O4+',
         implicit_species_flag = implicit_species_flag,
         charge = 4,
         mass = 29160.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O5+',
         implicit_species_flag = implicit_species_flag,
         charge = 5,
         mass = 29159.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O6+',
         implicit_species_flag = implicit_species_flag,
         charge = 6,
         mass = 29158.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O7+',
         implicit_species_flag = implicit_species_flag,
         charge = 7,
         mass = 29157.4,
         atomic_number = 8,
         scattering_flag = True,),
    dict(label = 'O8+',
         implicit_species_flag = implicit_species_flag,
         charge = 8,
         mass = 29156.4,
         atomic_number = 8,
         scattering_flag = True,),
    ####################################
    dict(label = 'H',
         implicit_species_flag = implicit_species_flag,
         charge = 0,
         mass = 1837.4,
         atomic_number = 1,
         scattering_flag = False,),
    dict(label = 'p',
         implicit_species_flag = implicit_species_flag,
         charge = 1,
         mass = 1836.2,
         atomic_number = 1,
         scattering_flag = True,),
    ####################################
    dict(label = 'e',
         implicit_species_flag = implicit_species_flag,
         charge = -1,
         mass = 1836.2,
         atomic_number = 1,
         scattering_flag = True,),];

h2o_creation_plasma = [
    dict(type='plasma',
         label = 'O+',
         species = 2,
         momentum_flags = (False, False, False),
         energy_flags = (False, False, False),),
    dict(type='plasma',
         label = 'p',
         species = 11,
         momentum_flags = (False, False, False),
         energy_flags = (False, False, False),),
    dict(type='plasma',
         label = 'e',
         species = 12,
         momentum_flags = (False, False, False),
         energy_flags = (False, False, False),),];

higherstate = dict(type='higherstate', lim='full', electron_species=12,
                   cross_sections = [0.0, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 0.0,
                                     0.0, 0.0, 0.0, 0.0,],
                   interval = 1);
h2o_creation_other = [
    #oxygen states
    sd(higherstate,
       label = 'O -> O+',
       species = 1,
       ion_species = 2,
       ionization_potential = 13.6),
    sd(higherstate,
       label = 'O+ -> O++',
       species = 2,
       ion_species = 3,
       ionization_potential = 35.1),
    sd(higherstate,
       label = 'O++ -> O3+',
       species = 3,
       ion_species = 4,
       ionization_potential = 54.9),
    sd(higherstate,
       label = 'O3+ -> O4+',
       species = 4,
       ion_species = 5,
       ionization_potential = 77.4),
    sd(higherstate,
       label = 'O4+ -> O5+',
       species = 5,
       ion_species = 6,
       ionization_potential = 113.9),
    sd(higherstate,
       label = 'O5+ -> O6+',
       species = 6,
       ion_species = 7,
       ionization_potential = 138.1),
    sd(higherstate,
       label = 'O6+ -> O7+',
       species = 7,
       ion_species = 8,
       ionization_potential = 739.4),
    sd(higherstate,
       label = 'O7+ -> O8+',
       species = 8,
       ion_species = 9,
       ionization_potential = 871.4),
    #good old good old
    sd(higherstate,
       label = 'H -> p',
       species = 10,
       ion_species = 11,
       ionization_potential = 13.6),];
    


