#PBS -l walltime=96:0:00
#PBS -l nodes=47:ppn=12
#PBS -N H2O-3d-5.4e+17
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=H2O-3d-5.4e+17
#source $HOME/.bashrc

#This outputs the name of the root node
#to the directory where you submitted this PBS job
echo $HOSTNAME > $PBS_O_WORKDIR/hostname.txt   
cat $PBS_NODEFILE | uniq > $PBS_O_WORKDIR/nodesfile.txt


cd $PBS_O_WORKDIR


mpiexec -n 560 ./lsp-10-3d $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.o.txt



