#!/usr/bin/env bash
CONDAFILE=~/conda
[ -n "$CONDAFILE" ] && source $CONDAFILE
[ ! -n "$WAITDELAY" ] && WAITDELAY=1;
DIR=$([ -n "$1" ] && echo "$1" || echo ".")
if [ ! -n "$OUTDIR" ]; then
    OUTDIR=$([ -n "$2" ] && echo "$2" || echo movne-laser)
fi
mkdir -p "$OUTDIR"
[ ! -n "$NPROCS" ] && NPROCS=1;
source ~/.bashrc

for i in $(ls "$DIR" | grep 'sclr[0-9]\+\.p4\.gz' | sort -V); do
    n=$(echo ${i#sclr*} | sed s/\.p4\.gz//)
    I=$(printf '%05d' "$n" )
    [ -e "$OUTDIR"/$I.png ] && [ ! -n "$DONTSKIP" ] && echo skipping...$i &&  continue;
    while [ $(pgrep -f 'python[23]* *.*sclrq.py' | wc -l ) -ge $NPROCS ]; do sleep $WAITDELAY; done;
    sleep 0.25;
    echo $i...
    sclrq.py -D "$DIR" $n "$OUTDIR"/$I.png --intensity="1.641532e+13" \
        -l --lims="(100000000000000.0, 1e+21)" --highlight="1.114855e+19" --laser -Q RhoN10 &
done
while [ $(pgrep python2 | wc -l ) -gt 0 ]; do
    echo waiting...
    sleep 5; done;
OUTMOV="10um-1.64e+14-l=19.2um-ne-laser.mp4"
ffmpeg -pattern_type glob -i "$OUTDIR/*.png" -c:v libx264 -pix_fmt yuv420p -y $OUTMOV
[ -e $OUTMOV ] && rcp $OUTMOV $PBS_O_WORKDIR
