#!/usr/bin/env bash

if [ -z "$1" ] || [ "$1" == "-h" ]; then
   echo "usage: mkhotwater3d <newdir>"
   echo ""
   echo "call in the sharks directory"
   exit 0
fi

mkdir -p "$1"
ln -s ../hotwater3d_tmpl/hotwater3d_tmpl.lsp $1/
ln -s ../hotwater3d_tmpl/hotwater3d_tmpl.pbs $1/
ln -s ../hotwater3d_tmpl/mkmovne_tmpl $1/
ln -s ../hotwater3d_tmpl/genpbs.py $1/
ln -s ../hotwater3d_tmpl/genlsp.py $1/
ln -s ../hotwater3d_tmpl/gendat.py $1/
ln -s ../hotwater3d_tmpl/gensim.py $1/
ln -s ../hotwater3d_tmpl/mklin.py $1/
cp hotwater3d_tmpl/*.dat hotwater3d_tmpl/mkmovneloop $1/
cp scripts/loopscript scripts/zipper scripts/autozipper $1/
cp hotwater3d_tmpl/genangular $1/
