#!/usr/bin/env bash

#longl_3e18
BASE=longl_3e18
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_5e17
BASE=longl_5e17
INTENSITY=5e17
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_1e19
BASE=longl_1e19
INTENSITY=1e19
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_skinny_3e18
BASE=longl_skinny_3e18
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-10, 10)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_skinny_5e17
BASE=longl_skinny_5e17
INTENSITY=5e17
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-10, 10)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_skinny_1e19
BASE=longl_skinny_1e19
INTENSITY=1e19
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-10, 10)"   \
    --res="(800,800)" \
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/


#longl_f20_3e18
BASE=longl_f20_3e18
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --fp="(-20,0,0)"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_f20_5e17
BASE=longl_f20_5e17
INTENSITY=5e17
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --fp="(-20, 0, 0)"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_f20_1e19
BASE=longl_f20_1e19
INTENSITY=1e19
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-40, 10,-20, 20)"   \
    --tlim="(-30, 0,-15, 15)"   \
    --res="(800,800)" \
    --fp="(-20, 0, 0)"\
    --description="long wavelength"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

###################################################################
#no preplasma
#longl_5e17_no-preplasma
BASE=longl_5e17_no-preplasma
INTENSITY=5e17
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-20, 20,-25, 25)"   \
    --tlim="(-10,10,-15, 15)"   \
    --res="(800,1000)" \
    --fp="(-5, 0, 0)"\
    --targetdat="nopreplasma-thicker.dat"\
    --description="long wavelength, no preplasma"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_3e18_no-preplasma
BASE=longl_3e18_no-preplasma
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-20, 20,-25, 25)"   \
    --tlim="(-10,10,-15, 15)"   \
    --res="(800,1000)" \
    --fp="(-5, 0, 0)"\
    --targetdat="nopreplasma-thicker.dat"\
    --description="long wavelength, no preplasma"\
    --time=500e-16 \
    --pext-species="(10,11)" \
    --step="8e-17" >$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/


#Longl_1e19_no-preplasma
BASE=longl_1e19_no-preplasma
INTENSITY=1e19
mkdir -p $BASE

./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-20, 20,-25, 25)"   \
    --tlim="(-10,10,-15, 15)"   \
    --res="(800,1000)" \
    --fp="(-5, 0, 0)"\
    --targetdat="nopreplasma-thicker.dat"\
    --description="long wavelength, no preplasma"\
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/


###################################################################
#longer

#longl_longer_2e17
BASE=longl_longer_2e17
#this intensity has a0 = 1.18 like 3e18W/cm^2 for 800nm light.
INTENSITY=2.12e17
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-45, 10,-20, 20)"   \
    --tlim="(-35, 0,-15, 15)"   \
    --res="(1100,800)"          \
    --targetdat="watercolumn-longer.dat" \
    --description="longer sim for long wavelength"      \
    --fp="(-20,0,0)"                     \
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/

#longl_longer_3e18
BASE=longl_longer_3e18
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-45, 10,-20, 20)"   \
    --tlim="(-35, 0,-15, 15)"   \
    --res="(1100,800)"          \
    --targetdat="watercolumn-longer.dat" \
    --description="longer sim for long wavelength"      \
    --fp="(-20,0,0)"                     \
    --step="8e-17">$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp *.dat $BASE/





###############################################################
# TNSA

BASE=longl_tnsa_3e18
INTENSITY=3e18
mkdir -p $BASE
./genlsp.py -I $INTENSITY -l 3e-6  -w 8.14e-6 \
    -T 120e-15                  \
    --lim="(-20, 20,-25, 25)"   \
    --tlim="(-10,10,-15, 15)"   \
    --res="(800,1000)" \
    --fp="(-5, 0, 0)"\
    --targetdat="nopreplasma-thicker.dat"\
    --description="long wavelength, no preplasma"\
    --time=1e-12 \
    --dumpinterval="5e-16" \
    --pext-species="(10,11)" \
    --step="1e-16" |\
    sed 's/^ *\(particle_movie.*$\)/;\1/'>$BASE/$BASE.lsp
./genpbs.py -p $BASE |\
    sed 's:../scripts/autozipper:../../scripts/autozipper:'\
    >$BASE/$BASE.pbs
cp nopreplasma-thicker.dat sine700points.dat $BASE/


