#PBS -l walltime=96:0:00
#PBS -l nodes=150:ppn=12
#PBS -N flashic_3da
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M ngirmang.1@osu.edu


PBSBASE=flashic_3da
#source $HOME/.bashrc

#This outputs the name of the root node
#to the directory where you submitted this PBS job
echo $HOSTNAME > $PBS_O_WORKDIR/hostname.txt   
cat $PBS_NODEFILE | uniq > $PBS_O_WORKDIR/nodesfile.txt


cd $PBS_O_WORKDIR


mpiexec -n 1800 ./lsp-10-3d $PBSBASE.lsp >$PBS_O_WORKDIR/$PBSBASE.o.txt

